services:
  opensearch-node:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx512m" # Forcing it to stay small
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - OPENSEARCH_HOST=opensearch-node
    depends_on:
      - opensearch-node
    volumes:
      - ./tests:/app/tests